export const jujutsuQuestions = [
  "Is your character a human?",
  "Is your character a jujutsu sorcerer?",
  "Is your character more connected to curses than sorcerers?",
  "Has your character been connected to Jujutsu High?",
  "Does your character have strong physical abilities?",
  "Does your character rely more on intelligence than raw power?",
  "Is your character connected to a known family or clan?",
  "Does your character usually fight at close range?",
  "Does your character usually fight from a distance?",
  "Does your character clearly use cursed energy?",

  "Does your character have a cursed technique?",
  "Can your character use a domain or domain-like ability?",
  "Is your character connected to an old or rare technique?",
  "Does your character usually fight without a weapon?",
  "Does your character use a weapon or cursed tool?",
  "Is your character known for high speed?",
  "Is your character known for strong defense?",
  "Does your character rely on deception or planning?",
  "Is your character usually calm?",
  "Is your character usually aggressive or violent?",

  "Is your character connected to Tokyo Jujutsu High?",
  "Is your character connected to Kyoto Jujutsu High?",
  "Is your character more like a teacher or older authority figure?",
  "Is your character connected to the Zenin family?",
  "Is your character connected to Sukuna?",
  "Is your character connected to Gojo?",
  "Is your character connected to Yuji?",
  "Is your character connected to Megumi?",
  "Did your character appear in or around the Shibuya events?",
  "Did your character play an important role in a major fight?",

  "Could your character be considered a villain?",
  "Could your character be considered one of the good guys?",
  "Is your character’s loyalty or position unclear?",
  "Does your character have an important past?",
  "Does your character have a clear personal goal?",
  "Does your character care about protecting others?",
  "Is your character selfish or mostly focused on themselves?",
  "Does your character enjoy fighting?",
  "Does your character seem afraid of death?",
  "Does your character have very high confidence?",

  "Is your character’s power connected to shadows?",
  "Is your character’s power connected to curses or spirits?",
  "Is your character’s power connected to the body?",
  "Is your character’s power connected to fire or heat?",
  "Is your character’s power connected to plants or nature?",
  "Is your character’s power connected to water or the sea?",
  "Is your character’s power connected to ice?",
  "Is your character’s power connected to blood?",
  "Is your character’s power connected to cutting or sharp attacks?",
  "Is your character’s power connected to the soul?",

  "Is your character a special grade curse or close to that level?",
  "Is your character not a normal human?",
  "Does your character have a non-human appearance?",
  "Does your character look human but still feel unnatural?",
  "Is your character connected to a vessel or host?",
  "Does your character have strong healing or recovery ability?",
  "Is your character extremely hard to defeat?",
  "Has your character lost an important fight?",
  "Has your character defeated a strong opponent?",
  "Did your character change the direction of the story?",

  "Is your character very popular among fans?",
  "Is your character generally liked by many fans?",
  "Is your character controversial or hated by some fans?",
  "Does your character have an emotional scene?",
  "Does your character have a very recognizable design?",
  "Does your character have light-colored hair?",
  "Does your character have dark-colored hair?",
  "Does your character often wear a school uniform?",
  "Does your character often wear non-school clothing?",
  "Does your character have a strange or unique visual feature?",

  "Is your character connected to an older era?",
  "Has your character existed for a very long time?",
  "Is your character younger than many powerful characters?",
  "Does your character have a lot of battle experience?",
  "Is your character considered talented or gifted?",
  "Did your character gain strength mostly through training?",
  "Is your character’s strength natural or inherited?",
  "Is your character directly connected to a powerful curse?",
  "Is your character connected to someone who died or disappeared?",
  "Does your character have an internal conflict?",

  "Does your character use strategy in battle?",
  "Does your character attack directly without thinking too much?",
  "Does your character try to provoke opponents?",
  "Is your character usually quiet?",
  "Is your character loud or expressive?",
  "Does your character have a funny side?",
  "Is your character usually very serious?",
  "Does your character have a scary side?",
  "Does your character have a kind side despite being powerful?",
  "Could your character trick other people easily?",

  "Did your character appear as an enemy at some point?",
  "Did your character switch sides or change role in the story?",
  "Is your character connected to a larger plan?",
  "Is your character considered one of the strongest in the story?",
  "Is your character’s power easy to understand?",
  "Is your character’s technique complicated or hard to explain?",
  "Does your character rely on teammates or allies?",
  "Does your character usually fight alone?",
  "Would a direct question reveal your character too quickly?",
  "Should questions about this character stay general at first?"
];

export const jujutsuQuestionsAr = [
  "هل الشخصية من البشر؟",
  "هل الشخصية تعتبر ساحر جوجوتسو؟",
  "هل الشخصية مرتبطة باللعنات أكثر من السحرة؟",
  "هل الشخصية ظهرت ضمن أحداث المدرسة؟",
  "هل الشخصية عندها قوة جسدية واضحة؟",
  "هل الشخصية تعتمد على الذكاء أكثر من القوة المباشرة؟",
  "هل الشخصية عندها علاقة بعائلة معروفة؟",
  "هل الشخصية أسلوبها في القتال قريب المدى؟",
  "هل الشخصية أسلوبها في القتال بعيد المدى؟",
  "هل الشخصية تستخدم طاقة ملعونة بشكل واضح؟",

  "هل الشخصية عندها تقنية ملعونة خاصة؟",
  "هل الشخصية قادرة على استخدام دومين؟",
  "هل الشخصية مرتبطة بتقنية قديمة أو نادرة؟",
  "هل الشخصية تقاتل غالبًا بدون سلاح؟",
  "هل الشخصية تستخدم سلاحًا أو أداة ملعونة؟",
  "هل الشخصية عندها سرعة عالية؟",
  "هل الشخصية عندها دفاع قوي؟",
  "هل الشخصية تعتمد على الخداع أو التخطيط؟",
  "هل الشخصية عندها شخصية هادئة؟",
  "هل الشخصية عصبية أو عدوانية غالبًا؟",

  "هل الشخصية من طلاب طوكيو؟",
  "هل الشخصية من طلاب كيوتو؟",
  "هل الشخصية تعتبر معلمًا أو شخصية أكبر سنًا؟",
  "هل الشخصية مرتبطة بعائلة زينين؟",
  "هل الشخصية عندها علاقة بسوكونا؟",
  "هل الشخصية عندها علاقة بغوجو؟",
  "هل الشخصية عندها علاقة بيوجي؟",
  "هل الشخصية عندها علاقة بميغومي؟",
  "هل الشخصية ظهرت في شيبويا؟",
  "هل الشخصية لعبت دورًا مهمًا في القتال؟",

  "هل الشخصية ممكن تعتبر شريرة؟",
  "هل الشخصية ممكن تعتبر من الطرف الجيد؟",
  "هل الشخصية موقفها غامض؟",
  "هل الشخصية عندها ماضٍ مهم؟",
  "هل الشخصية عندها هدف واضح؟",
  "هل الشخصية تهتم بحماية الآخرين؟",
  "هل الشخصية أنانية أو تفكر بنفسها أكثر؟",
  "هل الشخصية تحب القتال؟",
  "هل الشخصية تخاف من الموت؟",
  "هل الشخصية عندها ثقة عالية جدًا بنفسها؟",

  "هل الشخصية تملك قوة مرتبطة بالظلال؟",
  "هل الشخصية تملك قوة مرتبطة بالأرواح أو اللعنات؟",
  "هل الشخصية تملك قوة مرتبطة بالجسد؟",
  "هل الشخصية تملك قوة مرتبطة بالنار أو الحرارة؟",
  "هل الشخصية تملك قوة مرتبطة بالنباتات أو الطبيعة؟",
  "هل الشخصية تملك قوة مرتبطة بالماء أو البحر؟",
  "هل الشخصية تملك قوة مرتبطة بالجليد؟",
  "هل الشخصية تملك قوة مرتبطة بالدم؟",
  "هل الشخصية تملك قوة مرتبطة بالتقطيع أو الضربات الحادة؟",
  "هل الشخصية تملك قوة تؤثر على الروح؟",

  "هل الشخصية من اللعنات الخاصة؟",
  "هل الشخصية ليست إنسانًا عاديًا؟",
  "هل الشخصية عندها شكل غير بشري بالكامل؟",
  "هل الشخصية شكلها قريب من البشر لكنها ليست طبيعية؟",
  "هل الشخصية مرتبطة بجسم أو وعاء؟",
  "هل الشخصية عندها قدرة علاجية أو تعافي قوي؟",
  "هل الشخصية صعبة الهزيمة جدًا؟",
  "هل الشخصية خسرت قتالًا مهمًا؟",
  "هل الشخصية فازت ضد خصم قوي؟",
  "هل الشخصية كانت سببًا في تغيير مسار القصة؟",

  "هل الشخصية مشهورة بين جماهير الأنمي؟",
  "هل الشخصية محبوبة من أغلب الناس؟",
  "هل الشخصية مكروهة أو مثيرة للجدل؟",
  "هل الشخصية عندها لحظة مؤثرة؟",
  "هل الشخصية عندها تصميم مميز جدًا؟",
  "هل الشخصية شعرها فاتح اللون؟",
  "هل الشخصية شعرها غامق اللون؟",
  "هل الشخصية تلبس زي المدرسة غالبًا؟",
  "هل الشخصية تلبس ملابس غير مدرسية غالبًا؟",
  "هل الشخصية عندها علامة أو مظهر غريب واضح؟",

  "هل الشخصية مرتبطة بعصر قديم؟",
  "هل الشخصية موجودة منذ زمن طويل؟",
  "هل الشخصية أصغر سنًا من أغلب الشخصيات القوية؟",
  "هل الشخصية عندها خبرة قتالية كبيرة؟",
  "هل الشخصية تعتبر عبقرية أو موهوبة؟",
  "هل الشخصية قوتها تعتمد على تدريب كبير؟",
  "هل الشخصية قوتها فطرية أو موروثة؟",
  "هل الشخصية عندها علاقة مباشرة بلعنة قوية؟",
  "هل الشخصية عندها علاقة بشخص مات أو اختفى؟",
  "هل الشخصية عندها صراع داخلي؟",

  "هل الشخصية تستخدم استراتيجية أثناء القتال؟",
  "هل الشخصية تهاجم مباشرة بدون تفكير كثير؟",
  "هل الشخصية تحاول استفزاز الخصم؟",
  "هل الشخصية كلامها قليل غالبًا؟",
  "هل الشخصية تتكلم كثيرًا أو شخصيتها صاخبة؟",
  "هل الشخصية عندها حس فكاهي؟",
  "هل الشخصية جادة جدًا؟",
  "هل الشخصية عندها جانب مخيف؟",
  "هل الشخصية عندها جانب طيب رغم قوتها؟",
  "هل الشخصية ممكن تخدع الآخرين بسهولة؟",

  "هل الشخصية ظهرت كخصم في مرحلة ما؟",
  "هل الشخصية تحولت من عدو إلى حليف أو العكس؟",
  "هل الشخصية عندها علاقة بمخطط كبير؟",
  "هل الشخصية تعتبر من الأقوى في عالم جوجوتسو؟",
  "هل الشخصية قوتها مفهومة بسهولة؟",
  "هل تقنية الشخصية معقدة أو تحتاج شرح؟",
  "هل الشخصية تعتمد على فريق أو حلفاء؟",
  "هل الشخصية غالبًا تقاتل وحدها؟",
  "هل السؤال عن هذه الشخصية ممكن يكشفها بسرعة إذا كان مباشرًا؟",
  "هل الأفضل أن تكون الأسئلة عن هذه الشخصية عامة في البداية؟"
];
